### ISSUE TITLE
quick data access compents

### ISSUE THREAD

**Issue by PonyPC** [Fr0sT-Brutal/awesome-delphi#21]
svn://www.qdac.cc/QDAC3

site: http://blog.qdac.cc/?page_id=139

useful units such as QJson(a fastest and easy use json unit), QWorker(job delivery)

**Comment by Fr0sT-Brutal** [comment]
Do you have a web page on English? Chinese-only resource will have limited usage.

**Comment by PonyPC** [comment]
sorry, the author said he is not good at english, maybe he would add a translation later.
