### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by the-Arioch** [Fr0sT-Brutal/awesome-delphi#28]
1. Unified Interbase URL is wrong, it was moved to GitHub, see upstream in my profile
2. Consider Delphi-XmlLite wrapper - it provides much different workflow than both DOM and SAX
3. Jedi CodeLib and JediVCL (those are different while related libs) moved to GitHub too
4. Spring4D is not mentioned in encryption libraries section
5. Consider ODS/XLSX/XML-SS exporting library https://github.com/Avemey/zexmlss
6. for unit tests - add https://github.com/deltics/delphi.libs/tree/master/smoketest

**Comment by Fr0sT-Brutal** [comment]
1. Fixed
2. Added
3. Not confirmed, main links on their website still lead to SF.
4. Spring4D is in "General Libraries" section and encryption features are mentioned in description. I dislike the idea of duplicating links in the list so I don't see another good option for this case.
5. Nice, added
6. Added

**Comment by the-Arioch** [comment]
>  I dislike the idea of duplicating links in the list 

Me too, that is why I suggested to *mention* it. 
Not copy wit hURL, but just say "Spring4D mentioned above can do it too"

Reason: the guy wants an encryption lib, would he sieve through all th general-purpose ones ? Hardly so, he would only look into "Encryption" section.

....this actually demands something as tags or wiki categories, when one lib could be added into several sections automatically.

**Comment by the-Arioch** [comment]
http://www.delphifeeds.com/postings/104695-jcl_and_jvcl_have_completed_the_move_to_github

http://wiki.delphi-jedi.org/wiki/JCL_Download#Direct_access_to_our_version_control_system

And even menu at https://sourceforge.net/projects/jvcl/files/ has "git at GitHub" link

**Comment by the-Arioch** [comment]
Regarding XmlLite - I do not think the Genasis repo is still alive, I could not get reply from him neither on GitHub nor on StackOverflow. Also see his pull requests lingering for so long without any comments.
It was also full of bugs in c->Pascal translation.

**Comment by the-Arioch** [comment]
You listed GlibWMI, then I also suggest you MagWMI from http://www.magsys.co.uk/delphi/
Used it two years ago, had e-mail discussions with author of it.

**Comment by the-Arioch** [comment]
Also see http://www.cromis.net/blog/downloads/
SimpleStorage is an add-on to OmniXML
Chromis.IPC is classic for inter-process comm

Others might be good too

...at least they are alive

**Comment by the-Arioch** [comment]
FastMM moved too - https://github.com/pleriche/FastMM4

**Comment by the-Arioch** [comment]
IF you list SapMM then there is yet-another multithread-oriented Heap Manager
https://github.com/d-mozulyov/BrainMM
http://www.sql.ru/forum/1213139-18/ekstremalno-bystryy-menedzher-pamyati-brainmm

**Comment by the-Arioch** [comment]
Volga DB Pack - seems not bad, but looks like abandoned and subject to bit rot - https://sourceforge.net/projects/volgadb/

**Comment by the-Arioch** [comment]
http://openctf.sourceforge.net/ - one more testing framework, with accent on automatic tests
 
https://github.com/LaKraven/ - more for VLC, RAD-Split, LKSL (general library), FMX-VCL fusion

http://www.mitov.com/products/openwire - the framework for visually-connected datastreams, free (while more advanced components based upon it are not )

**Comment by the-Arioch** [comment]
for XML/JSON section - there is also YAML language

https://github.com/andreynering/delphi-yaml - wrapper


for scripting - not only JS/PasScript, there is also ppular Lua
https://github.com/d-mozulyov/CrystalLUA
https://github.com/danieleteti/lua4delphi/commits/master

**Comment by Fr0sT-Brutal** [comment]
Wow :) will take some time to sort all this links out...

**Comment by the-Arioch** [comment]
OTOH, now that there is Delphinus - is this list still so needed like it was few years ago ?

**Comment by the-Arioch** [comment]
I also failed to find TGridView - not the commercial Berg's one, but Russian one. It was updated in 2012 to XE2 - and seemingly dropped after that.

ZEXML-SS lib has its own advanced gird though, so maybe TGridView is not needed.

w.r.t. OXML lib... it can not be used in commercial programs for free like MPL/LGPL, it is kiond of nag-ware, so I wonder if this list policy is okay with that. Perhaps there is to be special note for libs, that are only free for free apps.

**Comment by the-Arioch** [comment]
http://www.yunqa.de/delphi/products/ucl/index - maybe an option for compression libs, where standardized foray for cross-vendors exchange is not needed

**Comment by Fr0sT-Brutal** [comment]
Almost all done.
Regarding JEDI, please feel free to list features they implement, because I couldn't find online docs and their codebase is really huge.
cromis.net and BaseForms are in TODO.

**Comment by the-Arioch** [comment]
> mORMot. RESTful ORM and SOA services via interfaces over high performance HTTP server, MVC/MVVM web sites

кстати, mORMot - это тогда тоже general библиотека

там до фига - от хранения данных в БД и до автоматического построения GUI и экспорта в PDF и скоростного парсинга JSON

**Comment by the-Arioch** [comment]
> VolgaDB. Pretty customizable DBgrid 

link broken

**Comment by the-Arioch** [comment]
> SuperObject. Parser/writer for JSON data format

BTW it can also read XML, though in a somewhat perverted way, but I did used it for parsing small snippets, just for being familiar with this lib and because its easy to use API :-)

**Comment by the-Arioch** [comment]
Старик Дeржавин вас заметил :-D  https://plus.google.com/102570002721714768273/posts/6Vu8FzbdoFg

**Comment by Fr0sT-Brutal** [comment]
:) стараемся...
