### ISSUE TITLE
This awesome list as Pascal language

### ISSUE THREAD

**Issue by leogregianin** [Fr0sT-Brutal/awesome-delphi#35]
Hi,
This awesome list has no predominant programming language, although not a software or script language but could be marked as Pascal.

GitHub determines the projects according to [this](https://github.com/github/linguist).

You could create a blank file with .pas extension to be recognized as pascal language and thus be better displayed :rocket:.

**Comment by Fr0sT-Brutal** [comment]
Well it's kind of trumpery and I dislike the idea of garbage files in the repo. It contains plenty of them already. I tried .gitattribute way as mentioned in Linguist readme with no luck. If you manage to get it working I'll merge the changes but empty .pas file is something I can't accept in my ideal world :)

**Comment by leogregianin** [comment]
What you did with .gitattributes will work. Apparently does not work with the README file, which I did "*.md linguist-language=Pascal"

**Comment by Fr0sT-Brutal** [comment]
Yeah, it worked, thanks for the tip
