### ISSUE TITLE
Graphics and gamedev

### ISSUE THREAD

**Issue by niuniomartinez** [Fr0sT-Brutal/awesome-delphi#41]
Hi,

Here you have two nice projects you may add to the list:

**Allegro.pas**
A wrapper to use the Allegro Game Library with Pascal compilers (Delphi, Free Pascal).  Version 4 stable, version 5 WIP.
https://www.sf.net/p/allegro-pas
https://github.com/niuniomartinez/allegro-pas

**Castle Engine**
The free open-source 3D and 2D game engine using modern Object Pascal.
https://castle-engine.sourceforge.io/

Regards.

**Comment by Fr0sT-Brutal** [comment]
Thanks! Damn I was sure I added these projects. At least their names are familiar to me.
Unfortunately Castle Engine seems to be FPC only, so it can't live in Delphi list.
