### ISSUE TITLE
suggested projects for inclusion. 

### ISSUE THREAD

**Issue by Xor-el** [Fr0sT-Brutal/awesome-delphi#42]
Hi,

Here are a few nice projects you may add to the list:

HashLib4Pascal

HashLib4Pascal is a Delphi/FreePascal compatible library that provides an easy to use interface for computing hashes and checksums of strings (with a specified encoding), files, streams, byte arrays and untyped data to mention but a few. It also supports Incremental Hashing.

https://github.com/Xor-el/HashLib4Pascal

TIntX

TIntX is a Pascal port of IntX arbitrary precision Integer library with fast, about O(N * log N) multiplication/division algorithms implementation. It provides all the basic arithmetic operations on Integers, comparing, bitwise shifting etc. It also allows parsing numbers in different bases and converting them to string, also in any base. The advantage of this library is its fast multiplication, division and from base/to base conversion algorithms. all the fast versions of the algorithms are based on fast multiplication of big Integers using Fast Hartley Transform which runs for O(N * log N * log log N) time instead of classic O(N^2).

https://github.com/Xor-el/IntXLib4Pascal

BaseNcodingPascal

Library for encoding of binary data into strings using base32, base85, base128 and other algorithms for FPC and Delphi.

https://github.com/Xor-el/BaseNcodingPascal

EmailValidationPascal

Simple Class for Validating Email Address Syntax in Pascal/Delphi

https://github.com/Xor-el/EmailValidationPascal

ByteSizeLibPascal

TByteSize is a utility "record" that makes byte size representation in code easier by removing ambiguity of the value being represented.

https://github.com/Xor-el/ByteSizeLibPascal

PatternFinderPascal

Signature matcher/wildcard pattern finder in Pascal.

https://github.com/Xor-el/PatternFinderPascal

Regards.

**Comment by Fr0sT-Brutal** [comment]
Thanks for these nice projects!
