### ISSUE TITLE
Two AT components

### ISSUE THREAD

**Issue by Alexey-T** [Fr0sT-Brutal/awesome-delphi#53]
Pls list 
-ATTabs
-ATBinHex - viewer for files of unlimited size like in Total Commander

**Comment by Alexey-T** [comment]
Repos Are in my github acc. ATBinHex is part of AtViewer too.

**Comment by Fr0sT-Brutal** [comment]
ATTabs added, thanks.
ATBinHex seems to be for Lazarus only? I found ATBinHex-Lazarus repo only.

**Comment by Alexey-T** [comment]
ATBinHex for Delphi: repo is part of https://github.com/Alexey-T/ATViewer
ATBinHex for Laz: https://github.com/Alexey-T/ATBinHex-Lazarus
