### ISSUE TITLE
Wolfgang Ehrhardt's crypto & hash libraries

### ISSUE THREAD

**Issue by jackdp** [Fr0sT-Brutal/awesome-delphi#55]
[http://www.wolfgang-ehrhardt.de/index.html](http://www.wolfgang-ehrhardt.de/index.html)
A large number of Delphi/Free Pascal units related mainly to maths, encryption and hashing. Many algorithms optimized in assembler.
I've tested many hash libraries for Pascal (including LockBox, DCPCrypt, HashLib4Pascal, DEC) and I have to say that Wolfgang's implementation is definitely the fastest.

**Comment by Fr0sT-Brutal** [comment]
Nice, thanks!
