### ISSUE TITLE
Delphi license manager (trial generator) VCL

### ISSUE THREAD

**Issue by AdminUser0** [Fr0sT-Brutal/awesome-delphi#56]
Purpose: Proposing introduction of a new library
Name of library: Proteus License Manager
Category: License Manager/Protection/Setup/Trial
Edition: all modern (unicode) Delphi editions, Lazarus and Delphi 7 supported with MINOR modifications.
Website: http://www.visualbioinformatics.com/Delphi%20VCL%20licensing%20system.html

Proteus library is a licensing system for Embarcadero Delphi programmers. Proteus helps you "sell" your program to your customers. With Proteus library you can create demo/trial versions of your application that are time-limited or feature-limited.
 

Typical usage
Deliver your application to your customers where it will work for a period of time (Trial period) then it will switch to Demo mode where program's functionality is severely crippled, or a "nag" screen is shown to encourage the customer to purchase a license.

Once the customers pays you email the Unlock Key to him. The customer enters the key and the program switches back from Trial/Demo to Fully-Functional mode.

**Comment by Fr0sT-Brutal** [comment]
This list is for open source projects. Proteus is commercial (and has hilariously severe identification requirements!)
