### ISSUE TITLE
You might want to look here...

### ISSUE THREAD

**Issue by MHumm** [Fr0sT-Brutal/awesome-delphi#58]
...in the development branch of this one:
https://github.com/winkelsdorf/DelphiEncryptionCompendium

If you look carefully enough you might spot signs of new activity in this project, including major work for getting it cross platform compatible. Further volunteers in that project are welcome by the way!
(means your no updates since 2010 comment could be obsolete in the future)

**Comment by Fr0sT-Brutal** [comment]
Thanks, the note is updated!
