### ISSUE TITLE
Spring4D. is not a Encryption Library, is a 

### ISSUE THREAD

**Issue by HeZiHang** [Fr0sT-Brutal/awesome-delphi#71]
The Spring Framework provides a comprehensive programming and configuration model for modern enterprise applications.
Spring4D is an open-source code library for Delphi . It consists of a number of of different modules that contain a base class library (common types, interface based collection types, reflection extensions) and a dependency injection framework.

**Comment by turric4n** [comment]
+1

**Comment by Fr0sT-Brutal** [comment]
In "Encryption" section where the library is mentioned in brief the link leads to "General Libraries" section where it described fully.
