### ISSUE TITLE
This repo needs more administrators.

### ISSUE THREAD

**Issue by turric4n** [Fr0sT-Brutal/awesome-delphi#73]
Hi,

Main administrator is not very active... This repo deserves more administrators to keep running.

Please do the possibility to add more administrators to this repository.

**Comment by Fr0sT-Brutal** [comment]
> Wise man said: "Only fools rush in"

I don't think the list of nice links needs 10 ns reaction time. Especially considering the low popularity of Delphi itself. You are free to create PR's, they are usually much faster to add.

**Comment by turric4n** [comment]
I don't think Delphi/Pascal low popularity isn't a reason to have only one administrator in an Awesome repository... But think about you lose your interest for this repo and abandon. Please think about this a little.

**Comment by Fr0sT-Brutal** [comment]
If I lose interest, I'll transfer the repo to someone. If I abandon GH, then I'm locked on a faraway no-man island.
See no problem here
